<a href="https://colab.research.google.com/github/MaximRubbit2/MALLlblHa/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_1_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 1

##Загрузка датасета
В файле classification datasets расположены ссылки на датасеты. Выберите один в соответствии со своим вариантом, скачайте и прочитайте файл

**Не забудьте загрузить нужные библиотеки**

Например: pip3 install pandas

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/global-data-on-sustainable-energy (1).csv')
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

##Первое знакомство с датасетом
В следующих ячейках выведите:


1.   Колонки датасета
2.   Первые 5 значений
3.   Последние 5 значений
4.   Статистику по числовым колонкам

In [ ]:
df.head(0)

In [ ]:
df.head(5)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

In [ ]:
df.tail(5)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.6802,10.00,11020.00046,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.0115,9.51,10340.00015,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.9858,9.83,12380.00011,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.6553,10.47,11760.00023,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.1318,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [ ]:
df.describe()

,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Land Area(Km2),Latitude,Longitude
count,3649.000000,3639.000000,3480.000000,2718.000000,1.560000e+03,3455.000000,3628.000000,3523.000000,3628.000000,3607.000000,3649.000000,3442.000000,3.221000e+03,1512.000000,3332.000000,3367.000000,3.648000e+03,3648.000000,3648.000000
mean,2010.038367,78.933702,63.255287,113.137498,9.422400e+07,32.638165,70.365003,13.450190,23.968010,36.801182,25743.981745,5.307345,1.598665e+05,11.986707,3.441610,13283.774348,6.332135e+05,18.246388,14.822695
std,6.054228,30.275541,39.043658,244.167256,2.981544e+08,29.894901,348.051866,73.006623,104.431085,34.314884,34773.221366,3.532020,7.736611e+05,14.994644,5.686720,19709.866716,1.585519e+06,24.159232,66.348148
min,2000.000000,1.252269,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.110000,1.000000e+01,0.000000,-62.075920,111.927225,2.100000e+01,-40.900557,-175.198242
25%,2005.000000,59.800890,23.175000,3.540000,2.600000e+05,6.515000,0.290000,0.000000,0.040000,2.877847,3116.737300,3.170000,2.020000e+03,2.137095,1.383302,1337.813437,2.571300e+04,3.202778,-11.779889
50%,2010.000000,98.361570,83.150000,32.910000,5.665000e+06,23.300000,2.970000,0.000000,1.470000,27.865068,13120.570000,4.300000,1.050000e+04,6.290766,3.559855,4578.633208,1.176000e+05,17.189877,19.145136
75%,2015.000000,100.000000,100.000000,112.210000,5.534750e+07,55.245000,26.837500,0.000000,9.600000,64.403792,33892.780000,6.027500,6.058000e+04,16.841638,5.830099,15768.615365,5.131200e+05,38.969719,46.199616
max,2020.000000,100.000000,100.000000,3060.190000,5.202310e+09,96.040000,5184.130000,809.410000,2184.940000,100.000010,262585.700000,32.570000,1.070722e+07,86.836586,123.139555,123514.196700,9.984670e+06,64.963051,178.065032

**Ответьте на следующие вопросы:**


1.   Какие средние значения в каждой числовой колонке вашего датасета?
2.   Минимальные и максимальные значения в каждой числовой колонке вашего датасета

In [ ]:
df.mean()

<ipython-input-12-c61f0c8f89b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()

Year                                                                2.010038e+03
Access to electricity (% of population)                             7.893370e+01
Access to clean fuels for cooking                                   6.325529e+01
Renewable-electricity-generating-capacity-per-capita                1.131375e+02
Financial flows to developing countries (US $)                      9.422400e+07
Renewable energy share in the total final energy consumption (%)    3.263816e+01
Electricity from fossil fuels (TWh)                                 7.036500e+01
Electricity from nuclear (TWh)                                      1.345019e+01
Electricity from renewables (TWh)                                   2.396801e+01
Low-carbon electricity (% electricity)                              3.680118e+01
Primary energy consumption per capita (kWh/person)                  2.574398e+04
Energy intensity level of primary energy (MJ/$2017 PPP GDP)         5.307345e+00
Value_co2_emissions_kt_by_country                                   1.598665e+05
Renewables (% equivalent primary energy)                            1.198671e+01
gdp_growth                                                          3.441610e+00
gdp_per_capita                                                      1.328377e+04
Land Area(Km2)                                                      6.332135e+05
Latitude                                                            1.824639e+01
Longitude                                                           1.482269e+01
dtype: float64

In [ ]:
df.min()

<ipython-input-13-c3612c624a3f>:1: FutureWarning: The default value of numeric_only in DataFrame.min is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.min()

Entity                                                              Afghanistan
Year                                                                       2000
Access to electricity (% of population)                                1.252269
Access to clean fuels for cooking                                           0.0
Renewable-electricity-generating-capacity-per-capita                        0.0
Financial flows to developing countries (US $)                              0.0
Renewable energy share in the total final energy consumption (%)            0.0
Electricity from fossil fuels (TWh)                                         0.0
Electricity from nuclear (TWh)                                              0.0
Electricity from renewables (TWh)                                           0.0
Low-carbon electricity (% electricity)                                      0.0
Primary energy consumption per capita (kWh/person)                          0.0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)                0.11
Value_co2_emissions_kt_by_country                                          10.0
Renewables (% equivalent primary energy)                                    0.0
gdp_growth                                                            -62.07592
gdp_per_capita                                                       111.927225
Land Area(Km2)                                                             21.0
Latitude                                                             -40.900557
Longitude                                                           -175.198242
dtype: object

In [ ]:
df.max()

<ipython-input-14-4c1ddf8920ff>:1: FutureWarning: The default value of numeric_only in DataFrame.max is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.max()

Entity                                                                  Zimbabwe
Year                                                                        2020
Access to electricity (% of population)                                    100.0
Access to clean fuels for cooking                                          100.0
Renewable-electricity-generating-capacity-per-capita                     3060.19
Financial flows to developing countries (US $)                      5202310000.0
Renewable energy share in the total final energy consumption (%)           96.04
Electricity from fossil fuels (TWh)                                      5184.13
Electricity from nuclear (TWh)                                            809.41
Electricity from renewables (TWh)                                        2184.94
Low-carbon electricity (% electricity)                                 100.00001
Primary energy consumption per capita (kWh/person)                      262585.7
Energy intensity level of primary energy (MJ/$2017 PPP GDP)                32.57
Value_co2_emissions_kt_by_country                                    10707219.73
Renewables (% equivalent primary energy)                               86.836586
gdp_growth                                                            123.139555
gdp_per_capita                                                       123514.1967
Land Area(Km2)                                                         9984670.0
Latitude                                                               64.963051
Longitude                                                             178.065032
dtype: object

##Типизация
Присвойте соответствующим колонкам один из типов (category, float, int)

In [ ]:
df.Year = df.Year.astype("category")
df.Year

0       2000
1       2001
2       2002
3       2003
4       2004
        ...
3644    2016
3645    2017
3646    2018
3647    2019
3648    2020
Name: Year, Length: 3649, dtype: category
Categories (21, int64): [2000, 2001, 2002, 2003, ..., 2017, 2018, 2019, 2020]

In [ ]:
koko = 'Access to electricity (% of population)'
df[koko] = df[koko].dropna().astype("float")
df[koko]

0        1.0
1        4.0
2        9.0
3       14.0
4       20.0
        ...
3644    42.0
3645    44.0
3646    45.0
3647    46.0
3648    52.0
Name: Access to electricity (% of population), Length: 3649, dtype: float64

In [ ]:
pok = 'gdp_growth'
df[pok] = df[pok].dropna().astype("int")
df[pok]

0       NaN
1       NaN
2       NaN
3       8.0
4       1.0
       ...
3644    0.0
3645    4.0
3646    4.0
3647   -6.0
3648   -6.0
Name: gdp_growth, Length: 3649, dtype: float64

Какие признаки вы можете выделить в своем датасете (категориальные, числовые и др., **минимум 3 разных**, помните что можно также выделить признаки более точно, например числовые - порядковые, количественные и т.д.)?

##Фильтрация
Офильтруйте 3 колонки вашего датасета и выведите результат

In [ ]:
df[df["Renewable-electricity-generating-capacity-per-capita"] > 2000]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
427,Bhutan,2007,71.0,54.65,2238.69,840000.0,92.07,0.0,0.0,6.49,...,21903.543,11.30,319.999993,NaN,18.0,1757.190496,20,38394.0,27.514162,90.433601
428,Bhutan,2008,67.0,57.80,2216.23,4250000.0,91.81,0.0,0.0,6.89,...,22370.271,11.12,300.000012,NaN,4.0,1828.154677,20,38394.0,27.514162,90.433601
429,Bhutan,2009,71.0,61.20,2194.18,82980000.0,92.38,0.0,0.0,6.93,...,22935.088,10.69,319.999993,NaN,6.0,1819.197310,20,38394.0,27.514162,90.433601
430,Bhutan,2010,73.0,63.90,2171.22,22890000.0,90.80,0.0,0.0,7.26,...,24284.154,10.11,400.000006,NaN,11.0,2258.186435,20,38394.0,27.514162,90.433601
431,Bhutan,2011,81.0,66.70,2146.80,90000.0,89.01,0.0,0.0,6.97,...,23369.613,9.47,589.999974,NaN,7.0,2563.261224,20,38394.0,27.514162,90.433601
432,Bhutan,2012,91.0,68.90,2121.45,3510000.0,87.32,0.0,0.0,6.74,...,22460.117,9.51,639.999986,NaN,5.0,2538.949519,20,38394.0,27.514162,90.433601
433,Bhutan,2013,87.0,71.20,2095.61,36930000.0,86.70,0.0,0.0,7.53,...,24615.076,9.41,670.000017,NaN,2.0,2472.724753,20,38394.0,27.514162,90.433601
434,Bhutan,2014,91.0,72.90,2069.91,1990000.0,86.54,0.0,0.0,7.15,...,23328.470,9.32,699.999988,NaN,5.0,2652.225654,20,38394.0,27.514162,90.433601
435,Bhutan,2015,95.0,75.00,2218.72,126110000.0,86.68,0.0,0.0,7.73,...,24203.820,8.70,769.999981,NaN,6.0,2752.630172,20,38394.0,27.514162,90.433601
436,Bhutan,2016,99.0,76.00,2192.15,50000.0,85.02,0.0,0.0,7.88,...,24692.543,8.30,930.000007,NaN,8.0,2930.574923,20,38394.0,27.514162,90.433601
437,Bhutan,2017,97.0,77.40,2166.11,20000.0,83.63,0.0,0.0,7.65,...,24327.346,8.06,970.000029,NaN,4.0,3286.596744,20,38394.0,27.514162,90.433601
438,Bhutan,2018,99.0,78.30,2141.06,110000.0,82.22,0.0,0.0,6.89,...,23138.410,8.22,1049.999952,NaN,3.0,3243.477437,20,38394.0,27.514162,90.433601
439,Bhutan,2019,100.0,79.40,3060.19,700000.0,82.27,0.0,0.0,8.95,...,27251.602,7.91,1049.999952,NaN,5.0,3322.863329,20,38394.0,27.514162,90.433601
440,Bhutan,2020,100.0,80.20,3026.40,NaN,NaN,0.0,0.0,8.95,...,26593.059,NaN,NaN,NaN,-10.0,3000.779327,20,38394.0,27.514162,90.433601

In [ ]:
df[df["gdp_growth"] == 8]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
3,Afghanistan,2003,14.0,9.50,8.09,25970000.0,36.66,0.31,0.00,0.63,...,229.96822,1.40,1220.000029,NaN,8.0,190.683814,60,652230.0,33.939110,67.709953
22,Albania,2001,100.0,40.50,NaN,NaN,NaN,0.13,0.00,3.52,...,8635.53200,3.89,3230.000000,NaN,8.0,1281.659826,105,28748.0,41.153332,20.168331
75,Angola,2012,37.0,45.20,35.16,10000.0,49.47,2.29,0.00,3.74,...,3615.52420,2.71,23870.000840,NaN,8.0,5100.097027,26,1246700.0,-11.202692,17.873887
108,Argentina,2003,96.0,96.45,234.82,50000.0,10.82,46.73,7.03,34.38,...,18326.52100,3.97,127660.003700,14.408259,8.0,3349.806300,17,2780400.0,-38.416097,-63.616672
110,Argentina,2005,96.0,97.50,234.67,280000.0,9.64,59.89,6.37,34.60,...,20232.84400,3.68,145990.005500,12.788524,8.0,5109.852245,17,2780400.0,-38.416097,-63.616672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3446,Ukraine,2007,99.0,93.90,NaN,NaN,2.39,93.13,92.54,10.47,...,34933.59000,9.78,312140.014600,1.836031,8.0,3197.934295,75,603550.0,48.379433,31.165580
3463,United Arab Emirates,2003,100.0,100.00,0.00,NaN,0.07,46.48,0.00,0.00,...,165507.60000,4.88,103819.999700,0.000000,8.0,33499.102780,118,83600.0,23.424076,53.847818
3553,Uzbekistan,2009,99.0,85.60,62.10,NaN,1.25,38.18,0.00,6.42,...,18643.18800,14.07,116529.998800,3.447852,8.0,1213.265328,79,447400.0,41.377491,64.585262
3571,Vanuatu,2006,26.0,14.50,2.80,NaN,63.75,0.04,0.00,0.00,...,1595.11000,2.48,70.000000,NaN,8.0,2049.532809,25,12189.0,-15.376706,166.959158
3614,Zambia,2007,18.0,16.10,134.61,30000.0,90.32,0.06,0.00,9.54,...,2793.33400,9.51,1980.000019,NaN,8.0,1124.290586,25,752618.0,-13.133897,27.849332

In [ ]:
df[df["Latitude"] <= 0]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
63,Angola,2000,24.0,41.1,14.37,NaN,73.44,0.50,0.0,0.90,...,1979.2562,3.68,16200.00000,NaN,3.0,556.838632,26,1246700.0,-11.202692,17.873887
64,Angola,2001,20.0,41.7,13.90,NaN,72.34,0.58,0.0,1.01,...,2079.7320,3.65,15960.00000,NaN,4.0,527.333529,26,1246700.0,-11.202692,17.873887
65,Angola,2002,26.0,41.7,13.46,NaN,70.42,0.58,0.0,1.13,...,2143.5280,3.34,15689.99958,NaN,13.0,872.494442,26,1246700.0,-11.202692,17.873887
66,Angola,2003,27.0,42.0,13.01,50000.0,65.14,0.71,0.0,1.23,...,2298.9023,3.49,16760.00023,NaN,2.0,982.961008,26,1246700.0,-11.202692,17.873887
67,Angola,2004,28.0,41.9,26.44,40000.0,61.92,0.45,0.0,1.73,...,2454.6700,3.17,17450.00076,NaN,10.0,1255.564513,26,1246700.0,-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.0,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.6802,10.00,11020.00046,NaN,0.0,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.0,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.0115,9.51,10340.00015,NaN,4.0,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.0,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.9858,9.83,12380.00011,NaN,4.0,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.0,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.6553,10.47,11760.00023,NaN,-6.0,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.0,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.1318,10.00,NaN,NaN,-6.0,1214.509820,38,390757.0,-19.015438,29.154857

##Группировка
Сгруппируйте датасет по какому-либо категориальному признаку и выведите среднее значение численных колонок (см. метод mean в pandas)

In [5]:
df.groupby(["Year"]).count()

,Entity,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
Year,,,,,,,,,,,,,,,,,,,,
2000,173,170,164,130,51,172,172,167,172,171,173,171,160,72,153,156,172,172,172,172
2001,172,170,164,129,51,171,171,166,171,170,172,171,160,72,154,157,172,172,172,172
2002,172,171,164,129,50,171,171,166,171,170,172,171,160,72,155,158,172,172,172,172
2003,172,171,164,129,52,171,171,166,171,170,172,171,160,72,156,158,172,172,172,172
2004,172,171,164,129,59,171,171,166,171,170,172,171,160,72,156,158,172,172,172,172
2005,172,171,164,129,64,171,171,166,171,170,172,171,160,72,157,158,172,172,172,172
2006,172,171,164,129,67,171,171,166,171,170,172,171,160,72,157,159,172,172,172,172
2007,174,174,166,129,66,173,173,168,173,172,174,173,162,72,160,161,174,174,174,174
2008,174,174,166,129,68,173,173,168,173,172,174,173,162,72,160,161,174,174,174,174
2009,174,174,166,129,80,173,173,168,173,172,174,173,162,72,160,161,174,174,174,174
2010,174,174,166,129,84,173,173,168,173,172,174,173,162,72,160,162,174,174,174,174
2011,174,174,166,129,87,173,173,168,173,172,174,173,162,72,160,162,174,174,174,174
2012,174,174,166,129,86,173,173,168,173,172,174,173,162,72,159,161,174,174,174,174
2013,175,175,167,130,94,174,174,169,174,173,175,174,163,72,160,163,175,175,175,175
2014,175,175,167,130,101,174,174,169,174,173,175,174,163,72,162,163,175,175,175,175
2015,175,175,167,130,99,174,174,169,174,173,175,174,163,72,162,163,175,175,175,175
2016,175,175,167,130,102,174,174,169,174,173,175,171,163,72,161,162,175,175,175,175
2017,175,175,167,130,106,174,174,169,174,173,175,171,159,72,161,162,175,175,175,175
2018,175,175,167,130,98,174,174,169,174,173,175,171,159,72,160,162,175,175,175,175
2019,175,175,167,130,94,174,174,169,174,173,175,171,159,72,160,161,175,175,175,175
2020,175,175,167,130,1,1,174,169,174,173,175,1,0,72,159,159,175,175,175,175

##Задание для гениев *
Агрегируйте числовой признак по категориальному признаку с использованием метода **без использования** библиотеки pandas, и вычислите медиану и среднее значение для каждой категории.

In [ ]:
#Агрегация